### ISSUE TITLE
Default image for all deployments

### ISSUE THREAD

**Issue by arifC** [kyma-incubator/examples#14]
Currently, all deployments in the Person Service example either have an image from "arifcrtsap" or "andy008" as default setting. The users are encouraged to replace this with their own image. However, it would be more consistent to have one image for all deployment files which does not depend on a specific dockerhub account.

**Expected result**
One consistent default image for all deployments which is not tied to a dockerhub account (e.g. from GCR).

**Actual result**
Deployments have default images from some personal dockerhub accounts.

**Comment by akrausesap** [comment]
This would also enable proper versioning
