### ISSUE TITLE
Update examples to Kyma 2.0

### ISSUE THREAD

**Issue by eduardoperez2151** [kyma-incubator/examples#43]
Hi team how`re you?
Could you update the examples to kyma 2.0 version?
Thanks a lot,
regards,
Eduardo.

**Comment by mmitoraj** [comment]
As far as I can see, the examples have not been maintained for about 2 years and most of them are really outdated. More up-to-date examples could be found in the [`kyma-project/examples`](https://github.com/kyma-project/examples) repository. I will update the issue if I get confirmation regarding plans for the `kyma-incubator/examples`. Thank you.

**Comment by mmitoraj** [comment]
@eduardoperez2151 I confirmed with @pbochynski that the up-to-date examples can be found in the main [kyma-project](https://github.com/kyma-project), especially in the [`kyma-project/examples`](https://github.com/kyma-project/examples) repository. I created an [issue](https://github.com/kyma-incubator/examples/issues/44) to do the clean-up in the `kyma-incubator/examples` repository.
