### ISSUE TITLE
Examples clean-up

### ISSUE THREAD

**Issue by mmitoraj** [kyma-incubator/examples#44]
**Description**

The examples in the `kyma-incubator/examples` repository are outdated. We should review the examples there and move those that are still useful to the main kyma-project and archive/delete other.

**Comment by mmitoraj** [comment]
I'm cleaning up the `kyma-incubator/examples` repository. I would like to archive all outdated examples and scenarios and move those that are relevant for Kyma to the `kyma-project/examples` repository.

Can you read through the examples related to your domain and confirm if the examples in the following directories are up-to-date or can be archived. Should I move any to the `kyma-project/examples`?
- @k15r, [`cloud-events-e2e-scenario`](cloud-events-e2e-scenario)
- @pbochynski , [`kubeconfig-for-sa`](https://github.com/kyma-incubator/examples/tree/master/kubeconfig-for-sa)
- @abbi-gaurav , [`kyma-local-e2e-scenario`](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario)
- @k15r, [`microservice-event-trigger`](https://github.com/kyma-incubator/examples/tree/master/microservice-event-trigger)
- @pbochynski, maybe you could help with [`personservice`](https://github.com/kyma-incubator/examples/tree/master/personservice)
- @pbochynski, [`tunnel`](https://github.com/kyma-incubator/examples/tree/master/tunnel)

Thank you in advance for your help!

**Comment by pbochynski** [comment]
I updated `kubeconfig-for-sa` example: https://github.com/kyma-incubator/examples/pull/46
Please archive `personservice` as it is too complex and outdated.
I will verify and update the tunnel example soon.

**Comment by pbochynski** [comment]
Tunnel example doesn't work any more and should be deleted: https://github.com/kyma-incubator/examples/pull/47

**Comment by abbi-gaurav** [comment]
I can check out if the e2e-local example can be updated. I will get back by Thursday.

**Comment by mmitoraj** [comment]
> I updated `kubeconfig-for-sa` example: #46 Please archive `personservice` as it is too complex and outdated. I will verify and update the tunnel example soon.

Thank you, PB. I reviewed your PR. Please see my suggestion. I'm archiving the `personservice` directory. 

> Tunnel example doesn't work any more and should be deleted: #47

I've approved the PR but still it requires a review by reviewers with write access.

**Comment by abbi-gaurav** [comment]
@mmitoraj , you can remove the e2e example. We have now application mocks and the manual steps are no longer required.
There are already blogs to use the application mocks with kyma.

**Comment by mmitoraj** [comment]
> @mmitoraj , you can remove the e2e example. We have now application mocks and the manual steps are no longer required. There are already blogs to use the application mocks with kyma.

I'm archiving the `kyma-local-e2e-scenario`. Thank you @abbi-gaurav for the confirmation.

**Comment by k15r** [comment]
`microservice-event-trigger` is outdated and can be removed
https://github.com/kyma-incubator/examples/tree/master/cloud-events-e2e-scenario is also outdated and should be removed

**Comment by mmitoraj** [comment]
> `microservice-event-trigger` is outdated and can be removed https://github.com/kyma-incubator/examples/tree/master/cloud-events-e2e-scenario is also outdated and should be removed

Thank you @k15r, I'm archiving both.
